name: flutter_list_view
description: Provide enhanced list view include jump index, keep position etc.
version: 1.1.30
homepage: https://github.com/robert-luoqing/flutter_list_view

environment:
  flutter: '>=3.32.0'
  sdk: '>=3.7.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
